// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDpCBsen93cVgQSaWqi3eMij3kk2HF_yAQ',
    appId: '1:145294845556:web:9ef166e06a6ddeead8d321',
    messagingSenderId: '145294845556',
    projectId: 'bank-b6112',
    authDomain: 'bank-b6112.firebaseapp.com',
    storageBucket: 'bank-b6112.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBVzAeIL006DAU3shOA1dduQxGkDJ6KPoo',
    appId: '1:145294845556:android:d7c5b61707ec330fd8d321',
    messagingSenderId: '145294845556',
    projectId: 'bank-b6112',
    storageBucket: 'bank-b6112.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAhtZ1dB4TtIdOoC3HV_DFaJWwqCLhfVjs',
    appId: '1:145294845556:ios:7ca0e5bec85bd3f0d8d321',
    messagingSenderId: '145294845556',
    projectId: 'bank-b6112',
    storageBucket: 'bank-b6112.firebasestorage.app',
    iosBundleId: 'com.example.securebank',
  );
}
